# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171025_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(max_length=50000, verbose_name='内容')),
                ('img_url', models.CharField(max_length=200, verbose_name='照片位置')),
            ],
        ),
    ]
