# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171025_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.FileField(upload_to='blog/static/photos/2017-10-27', verbose_name='照片'),
        ),
    ]
