# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171030_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
    ]
